### ISSUE TITLE
No input file specified.-after hosting

### ISSUE THREAD

**Issue by saifurrahman** [kookoolib/KooKooVBX#1]
HI
   I am using PHP5.2+ server and while click on the hosted URL,I am getting  "No input file specified."
Please help me to install OpenVBX for kookoo.
I have downloaded from the following url https://github.com/kookoolib/KooKooVBX

Regards
Saifur Rahman
Co-founder http://glomindz.com

**Comment by kookoolib** [comment]
Hi,Did you follow this link to complete KooKooVBX installationhttps://github.com/kookoolib/KooKooVBX/blob/master/INSTALL.markdownPlease confirm this and let us know the hosted URL which you are trying to open.Thanks & RegardsKooKoo Support

-------- Original Message --------
Subject: [KooKooVBX] No input file specified.-after hosting (#1)
From: saifurrahman
reply@reply.github.com
Date: Sun, July 22, 2012 9:41 pm
To: KooKoo support@kookoo.in
HI
   I am using PHP5.2+ server and while click on the hosted URL,I am getting  "No input file specified."
Please help me to install OpenVBX for kookoo.
I have downloaded from the following url https://github.com/kookoolib/KooKooVBX
Regards
Saifur Rahman

## Co-founder http://glomindz.com

**Comment by saifurrahman** [comment]
Yes, I am using the the same url 
https://github.com/kookoolib/KooKooVBX/blob/master/INSTALL.markdown
for installation guide and i have downloaded the zip file from https://github.com/kookoolib/KooKooVBX
and host at the following url
http://glomindz.com/test/KooKooVBX/

Regards
Saifur Rahman
Co-founder http://glomindz.com

**Comment by kookoolib** [comment]
HiSeems like you are hosted on godaddy server so did you try changing thisInstalling on Godaddy ?Add this to the bottom of KooKooVBX/config/config.php $config['uri_protocol'] = 'REQUEST_URI'; $config['index_page'] = '';Thanks & RegardsKooKoo Support

-------- Original Message --------
Subject: Re: [KooKooVBX] No input file specified.-after hosting (#1)
From: saifurrahman
reply@reply.github.com
Date: Sun, July 22, 2012 10:32 pm
To: KooKoo support@kookoo.in
Yes, I am using the the same url https://github.com/kookoolib/KooKooVBX/blob/master/INSTALL.markdown
for installation guide and i have downloaded the zip file from https://github.com/kookoolib/KooKooVBX
and host at the following urlhttp://glomindz.com/test/KooKooVBX/
Regards
Saifur Rahman

## Co-founder http://glomindz.com

**Comment by saifurrahman** [comment]
Thanks KooKoo support,
its working on bigrock server, but i could not able to find the reason why it not working on goddady.
anyway thanks

Regards
Saifur Rahman
Co-founder http://glomindz.com
